/*
 * This source file was generated by the Gradle 'init' task
 */
package database.spice;

public class App {

  public static void main(String[] args) {
    System.out.println("전세계 향신료 분석 서비스: 라따뚜이");
  }
}
